//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.UnityRosInterfaces
{
    [Serializable]
    public class ResetResponse : Message
    {
        public const string k_RosMessageName = "unity_ros_interfaces/Reset";
        public override string RosMessageName => k_RosMessageName;

        public bool done;

        public ResetResponse()
        {
            this.done = false;
        }

        public ResetResponse(bool done)
        {
            this.done = done;
        }

        public static ResetResponse Deserialize(MessageDeserializer deserializer) => new ResetResponse(deserializer);

        private ResetResponse(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.done);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.done);
        }

        public override string ToString()
        {
            return "ResetResponse: " +
            "\ndone: " + done.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize, MessageSubtopic.Response);
        }
    }
}
