//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.UnityRosInterfaces
{
    [Serializable]
    public class ResetRequest : Message
    {
        public const string k_RosMessageName = "unity_ros_interfaces/Reset";
        public override string RosMessageName => k_RosMessageName;

        public Geometry.PoseMsg amr_start;
        public Geometry.PointMsg amr_goal;

        public ResetRequest()
        {
            this.amr_start = new Geometry.PoseMsg();
            this.amr_goal = new Geometry.PointMsg();
        }

        public ResetRequest(Geometry.PoseMsg amr_start, Geometry.PointMsg amr_goal)
        {
            this.amr_start = amr_start;
            this.amr_goal = amr_goal;
        }

        public static ResetRequest Deserialize(MessageDeserializer deserializer) => new ResetRequest(deserializer);

        private ResetRequest(MessageDeserializer deserializer)
        {
            this.amr_start = Geometry.PoseMsg.Deserialize(deserializer);
            this.amr_goal = Geometry.PointMsg.Deserialize(deserializer);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.amr_start);
            serializer.Write(this.amr_goal);
        }

        public override string ToString()
        {
            return "ResetRequest: " +
            "\namr_start: " + amr_start.ToString() +
            "\namr_goal: " + amr_goal.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
